PLUGIN_NAME=		wg-ipv6-gateway
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		WireGuard IPv6 gateway companion - route management and health mirroring
PLUGIN_MAINTAINER=	bflood@users.noreply.github.com
PLUGIN_DEPENDS=		os-wireguard

.include "../../Mk/plugins.mk"
