PLUGIN_NAME=		wg-client-tunnels
PLUGIN_VERSION=		3.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		WireGuard upstream tunnels: create, edit, remove, rebind, adopt, sentinel
PLUGIN_MAINTAINER=	23534755+cayossarian@users.noreply.github.com
PLUGIN_WWW=		https://legotypes.github.io/wg-upstream-tunnels/

.include "../../Mk/plugins.mk"
