PLUGIN_NAME=		wg-client-tunnels
PLUGIN_VERSION=		2.2
PLUGIN_COMMENT=		WireGuard IPv6 gateway companion - route management and health mirroring
PLUGIN_MAINTAINER=	23534755+cayossarian@users.noreply.github.com
PLUGIN_DEPENDS=		os-wireguard

.include "../../Mk/plugins.mk"
