[start]
command:/usr/local/opnsense/scripts/OPNsense/WGIPv6Gateway/wgipv6gw.sh start
parameters:
type:script
message:starting WireGuard IPv6 gateway routes

[stop]
command:/usr/local/opnsense/scripts/OPNsense/WGIPv6Gateway/wgipv6gw.sh stop
parameters:
type:script
message:stopping WireGuard IPv6 gateway routes

[restart]
command:/usr/local/opnsense/scripts/OPNsense/WGIPv6Gateway/wgipv6gw.sh restart
parameters:
type:script
message:restarting WireGuard IPv6 gateway routes

[configure_routes]
command:/usr/local/opnsense/scripts/OPNsense/WGIPv6Gateway/wgipv6gw.sh configure_routes
parameters:
type:script
message:reconfiguring WireGuard IPv6 gateway routes

[status]
command:/usr/local/opnsense/scripts/OPNsense/WGIPv6Gateway/wgipv6gw.sh status
parameters:
type:script_output
message:requesting WireGuard IPv6 gateway status

[health_mirror]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/WGIPv6Gateway/health_mirror.php
parameters:
type:script
message:mirroring IPv4 health to IPv6 gateways
