###################################################################
# Local syslog-ng configuration filter definition [wgclienttunnels].
###################################################################
filter f_local_wgclienttunnels {
    program("wgct") or message("^\\[wgct-");
};
