[status]
command:/usr/local/opnsense/scripts/OPNsense/MacAliasCache/macalias.py status
parameters:
type:script_output
message:MAC alias cache status

[flush]
command:/usr/local/opnsense/scripts/OPNsense/MacAliasCache/macalias.py flush
parameters:
type:script_output
message:MAC alias cache flush
