###################################################################
# Local syslog-ng configuration filter definition [wanfailover].
###################################################################
filter f_local_wanfailover {
    program("wanfailover");
};
