PLUGIN_NAME=		wan-failover
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		WAN failover: hold a lossy WAN down until it is clean, move flows back, restart Tailscale on a real route change
PLUGIN_MAINTAINER=	23534755+cayossarian@users.noreply.github.com
PLUGIN_WWW=		https://legotypes.github.io/

.include "../../Mk/plugins.mk"
