PLUGIN_NAME=		mac-alias-cache
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Rebuild MAC firewall aliases from current host discovery data
PLUGIN_MAINTAINER=	23534755+cayossarian@users.noreply.github.com
PLUGIN_WWW=		https://legotypes.github.io/mac-alias-cache/

.include "../../Mk/plugins.mk"
