PLUGIN_NAME=		mac-alias-cache
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Rebuild MAC firewall aliases from current host discovery data
PLUGIN_MAINTAINER=	bflood@users.noreply.github.com

.include "../../Mk/plugins.mk"
